version: '3.4'

services:
  accountservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      - "443"
    volumes:
    - ~/.aspnet/https:/root/.aspnet/https:ro
    - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  warehouse:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      - "443"
    volumes:
    - ~/.aspnet/https:/root/.aspnet/https:ro
    - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
